name: macOS build & release

on:
  workflow_dispatch: {}          # manual runs
  push:
    tags: ['v*']                 # e.g. v1.0.0

permissions:
  contents: write                # needed for publishing releases

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - runner: macos-14     # Apple Silicon
            arch: arm64
          - runner: macos-13     # Intel
            arch: x86_64
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pyinstaller-hooks-contrib

      - name: Syntax check (fail fast)
        run: |
          python -m py_compile mag_panel.py
          python -m py_compile pg_admin_gui.py

      # ---- Main app (Qt / PySide6) ----
      - name: Build MAG Config.app (Qt, bundle all PySide6)
        run: |
          pyinstaller --noconfirm --windowed \
            --collect-all PySide6 \
            --name "MAG Config" mag_panel.py \
            --add-data "template.xlsx:."
      # Optional: smoke test in offscreen mode to reveal plugin issues in logs
      - name: Smoke test MAG Config (offscreen)
        run: |
          QT_DEBUG_PLUGINS=1 QT_QPA_PLATFORM=offscreen \
            "dist/MAG Config.app/Contents/MacOS/MAG Config" || true

      # ---- Admin app (Tk) ----
      - name: Build PG Admin GUI.app (Tk)
        run: |
          pyinstaller --noconfirm --windowed \
            --name "PG Admin GUI" pg_admin_gui.py

      # ---- Package & upload artifacts ----
      - name: Zip apps (preserve mac metadata)
        run: |
          ditto -c -k --sequesterRsrc --keepParent "dist/MAG Config.app" "MAG-Config-macOS-${{ matrix.arch }}.zip"
          ditto -c -k --sequesterRsrc --keepParent "dist/PG Admin GUI.app" "PG-Admin-GUI-macOS-${{ matrix.arch }}.zip"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-apps-${{ matrix.arch }}
          path: |
            MAG-Config-macOS-${{ matrix.arch }}.zip
            PG-Admin-GUI-macOS-${{ matrix.arch }}.zip

      # ---- Publish on tag ----
      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            MAG-Config-macOS-${{ matrix.arch }}.zip
            PG-Admin-GUI-macOS-${{ matrix.arch }}.zip
